# Generated by Django 4.2.18 on 2025-01-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TourismInvestment',
            fields=[
                ('investment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('number_of_projects', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('foreign_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('local_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='TourismIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tourists', models.IntegerField()),
                ('average_expenditure_month', models.FloatField()),
                ('average_expenditure_day', models.FloatField()),
                ('total_value', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='TourismAccomodationInvestment',
            fields=[
                ('investment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('number_of_projects', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('total_investment', models.IntegerField()),
                ('foreign_investment', models.IntegerField()),
                ('local_investment', models.IntegerField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceQualityDistribution',
            fields=[
                ('service_quality_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_quality', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='RoomQualityDistribution',
            fields=[
                ('room_quality_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_quality', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDistribution',
            fields=[
                ('room_distribution_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_status', models.CharField(max_length=100)),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_projects', models.IntegerField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredRestaurants',
            fields=[
                ('restaurant_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('establishments', models.IntegerField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryFinalPortOfDeparture',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('port_of_departure', models.CharField(max_length=100)),
                ('number_of_passengers', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='FoodQualityDistribution',
            fields=[
                ('food_quality_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('food_quality', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionOfTourismServices',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionTypeDistribution',
            fields=[
                ('attraction_type_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('number_of_foreign_visitors', models.IntegerField()),
                ('number_of_local_visitors', models.IntegerField()),
                ('local_visitor_income', models.FloatField()),
                ('foreign_visitor_income', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionStats',
            fields=[
                ('attraction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('visitors', models.JSONField(default=dict)),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AirConnectivityDistribution',
            fields=[
                ('air_connectivity_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('number_of_passengers', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AgeCategoryDistribution',
            fields=[
                ('age_category_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age_category', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationTypeDistribution',
            fields=[
                ('accomodation_type_distribution_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type_of_accomodation', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationCategorization',
            fields=[
                ('category_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('categorization', models.CharField(max_length=100)),
                ('establishments', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='QualityMetrics',
            fields=[
                ('metric_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('ROOM', 'Room Quality'), ('FOOD', 'Food Quality'), ('SERVICE', 'Service Quality')], max_length=20)),
                ('quality_level', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
            options={
                'unique_together': {('timeframe', 'metric_type', 'quality_level')},
            },
        ),
        migrations.CreateModel(
            name='CategoryDistribution',
            fields=[
                ('category_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('ACCOMMODATION', 'Accommodation Type'), ('AGE', 'Age Category')], max_length=20)),
                ('category_value', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
            options={
                'unique_together': {('timeframe', 'category_type', 'category_value')},
            },
        ),
        migrations.CreateModel(
            name='AllCountryStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
                ('days_of_stay', models.IntegerField(default=0)),
                ('purpose_of_visit', models.CharField(default='Not Specified', max_length=100)),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristats.timeframe')),
            ],
            options={
                'unique_together': {('country_id', 'timeframe')},
            },
        ),
    ]
