# Generated by Django 4.2.18 on 2025-01-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcountrystats',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='allcountrystats',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
